export const SLA_CONFIG = {
  name: "SLA",
  endpoint: "/sla",
  columns: [
    {
      header: "N°",
      key: "index",
      editable: false,
      mapFrom: (item, index) => index + 1,
    },
    {
      header: "Nombre",
      backendKey: "name",
      editable: true,
      required: true,
      validation: /^[a-zA-Z0-9\s\-_.]+$/,
      validationMessage: "Solo letras, números, espacios, guiones y puntos.",
    },
    {
      header: "Descripción",
      backendKey: "description",
      editable: true,
      type: "textarea",
      required: true,
    },
    {
      header: "Referencia",
      backendKey: "reference",
      editable: true,
      required: true,
    },
    {
      header: "Unidad Límite",
      backendKey: "expect_limit",
      editable: true,
      required: true,
      placeholder: "%, ms, s, min, h",
    },
    {
      header: "Objetivo Esperado",
      backendKey: "expect_target",
      type: "number",
      editable: true,
      required: true,
    },
    {
      header: "Objetivo Mínimo",
      backendKey: "minimun_target",
      type: "number",
      editable: true,
      required: true,
    },
    {
      header: "Algoritmo",
      backendKey: "algorithm",
      editable: true,
      required: true,
    },
    {
      header: "Herramienta",
      backendKey: "tool",
      editable: true,
      required: true,
    },
    {
      header: "Periodo Reporte (días)",
      backendKey: "report_period",
      type: "number",
      editable: true,
      required: true,
    },
    {
      header: "Mejora",
      backendKey: "improvement",
      type: "number",
      editable: true,
      required: true,
    },
    {
      header: "Riesgo",
      backendKey: "risk",
      type: "number",
      editable: true,
      required: true,
    },
    {
      header: "Pool de Riesgo",
      backendKey: "risk_pool",
      type: "number",
      editable: true,
      required: true,
    },
    {
      header: "Fecha Inicio",
      backendKey: "start_d",
      type: "date",
      editable: true,
      required: true,
      mapFrom: (item) =>
        item.start_d ? new Date(item.start_d).toLocaleDateString("es-CO") : "",
    },
    {
      header: "Fecha Fin",
      backendKey: "end_d",
      type: "date",
      editable: true,
      required: true,
      mapFrom: (item) =>
        item.end_d ? new Date(item.end_d).toLocaleDateString("es-CO") : "",
    },
    {
      header: "Tipo",
      backendKey: "type",
      type: "number",
      editable: true,
      required: true,
    },
    {
      header: "Meses Penalidad",
      backendKey: "months_penality",
      type: "number",
      editable: true,
      required: true,
    },
    {
      header: "Recargo %",
      backendKey: "recargo_percentage",
      type: "number",
      editable: true,
      required: true,
    },
    {
      header: "Contrato",
      backendKey: "contract_id",
      type: "select",
      editable: true,
      required: true,
      hiddenInTable: false,
      options: [],
      mapFrom: (item) => item.contract_name || item.contract_id,
    },
    {
      header: "Servicio",
      backendKey: "service_id",
      type: "select",
      editable: true,
      required: true,
      hiddenInTable: false,
      options: [],
      mapFrom: (item) => item.service_name || item.service_id,
    },
    {
      header: "Ventana Mantenimiento",
      backendKey: "mwindow_id",
      type: "select", // Idealmente select si tenemos el servicio de ventanas
      editable: true,
      required: true,
      options: [],
      mapFrom: (item) => item.mwindow_name || item.mwindow_id,
    },
    {
      header: "Estado",
      backendKey: "active",
      type: "select",
      options: [
        { value: 1, label: "Activo" },
        { value: 0, label: "Inactivo" },
      ],
      editable: true,
      required: false, // Default en backend
      hiddenInTable: true,
      hideInForm: true, // Ocultar en el formulario de creación
      mapFrom: (item) => (item.active === 1 ? "Activo" : "Inactivo"),
    },
  ],
};
